version: '3.4'

services:
  effecttscore:
    image: effecttscore
    build:
      context: shadcn
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
